name: Build and Release

on: push

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.0
        id: go

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2

      - name: Install Packages
        run: |
          sudo apt-get install libgtk-3-dev -y
          sudo apt-get install libz-mingw-w64-dev

      - name: Build for Linux
        run: |
          ./scripts/build_linux.sh

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          path: yomitan-import-linux
          name: yomitan-import-linux

      - name: Build for Windows
        run: |
          ./scripts/build_windows.sh

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          path: yomitan-import-windows
          name: yomitan-import-windows

      - name: Release on Tag Creation
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            yomitan-import-linux.zip
            yomitan-import-windows.zip
          draft: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
